baseURL = 'https://opiasec.github.io'
languageCode = 'en-us'
title = 'opiasec'
theme = 'gokarna-hugo'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
    [languages.en]
        [languages.en.params]
            homeSubtitle = "delivering security through culture"

[params]
    [[params.socialLinks]]
        name = "github"
        url = "https://github.com/opiasec"