baseURL = 'https://opiasec.com'
languageCode = 'en-us'
title = 'opiasec'
theme = 'hugo-coder'
defaultContentLanguage = 'en'
enableEmoji = true

[params]
    description = 'delivering security through culture'
    info = 'delivering security through culture'
    author = 'opiasec'
    colorScheme = 'dark'
    avatarURL = 'images/logo.jpeg'

    hideColorSchemeToggle = true
    faviconSVG = '/images/favicon.svg'

[[params.social]]
    name = 'github'
    url = 'https://github.com/opiasec'
    icon = 'fa-brands fa-github fa-2x'

[[params.social]]
    name = 'twitter'
    url = 'https://twitter.com/opiasec'
    icon = 'fa-brands fa-twitter fa-2x'
[[params.social]]
    name = 'Discord'
    url = 'https://discord.gg/hXdwCW7e87'
    icon = 'fa-brands fa-discord fa-2x'

    
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 2
[[menu.main]]
    name = 'Docs'
    url = 'https://docs.opiasec.com'
    weight = 3
[[menu.main]]
    name = 'Github'
    url = 'https://github.com/opiasec'
    weight = 4
